server:
  port: 8092

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update        # create, update, validate, none
    show-sql: true            # ????? SQL ? ???????
    properties:
      hibernate.format_sql: true

